openapi: "3.0.0"
info: { }

paths: { }

components:
  schemas:
    ApCollide:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        additionalProperties:
          type: string
