openapi: "3.0.0"
info: { }

paths: { }

components:
  schemas:
    MapAdditionalProperties:
      type: object
      required:
        - name
      properties:
        name:
          type: string
      additionalProperties:
        type: object
        additionalProperties:
          type: string
