openapi: "3.0.0"
info: { }

paths: { }

components:
  schemas:
    Payment:
      type: object
      required:
        - amount
      properties:
        amount:
          type: number
          format: decimal
