openapi: "3.0.0"
info: { }

paths: { }

components:
  schemas:
    RoleId:
      description: |
        The id for a role.
      type: integer

    LocalVariableClashes:
      properties:
        i:
          description: |
            Property which clashes with standard local variables
          type: array
          items:
            type: string
            nullable: true
        val:
          type: string
