openapi: "3.0.0"
info: { }

paths: { }

components:
  schemas:
    User:
      type: object
      required:
        - id
        - username
      properties:
        id:
          type: string
        username:
          type: string
          nullable: true
        email:
          type: string
    Tags:
      type: array
      items:
        type: string
