openapi: "3.0.0"
info: { }

paths: { }

components:
  schemas:
    Product:
      type: object
      required:
        - price
      properties:
        price:
          type: number
        weight:
          type: number
          format: float
        volume:
          type: number
          format: double
