openapi: "3.1.0"
info: { }

paths: { }

components:
  schemas:
    NumberValues:
      type: string
      enum:
        - 1
        - 2
    Holder:
      type: object
      properties:
        numberValue:
          $ref: '#/components/schemas/NumberValues'
