openapi: "3.0.0"
info: { }

paths: { }

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        author:
          type: string
      xml:
        name: "xml-book"

    BookProp1:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
          xml:
            name: "xml-title"
            attribute: true
        author:
          type: string

    BookProp2:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
          xml:
            name: "xml-title"
        author:
          type: string

    ContainerStandardArray:
      properties:
        books:
          type: array
          items:
            type: string

    ContainerWrappedArray:
      properties:
        books:
          type: array
          items:
            type: string
            xml:
              name: "item"
          xml:
            name: "book-array"
            wrapped: true

    ContainerArray:
      properties:
        books:
          type: array
          items:
            type: string
          xml:
            wrapped: false